@localhost=localhost:4004/odata/v4/main
@id=14101219-2c0f-485b-8475-f09253327210



GET http://{{localhost}}/Customers
Content-Type: application/json


###

POST http://{{localhost}}/Customers
Content-Type: application/json

{
    "id": "{{id}}",
    "firstName": "Pedro",
    "lastName": "Victor",
    "email": "pedro.assis@numenit.com"
}

###


DELETE  http://{{localhost}}/Customers(id={{id}})
Content-Type: application/json

###

PUT http://{{localhost}}/Customers(id={{id}})
Content-Type: application/json

###
# Buscando dados com search

GET http://{{localhost}}/Customers?$search=14101219
Content-Type: application/json

###
# Ordenando dados com orderby

GET http://{{localhost}}/Customers?$orderby=firstName desc
Content-Type: application/json

{
    "firstName": "Jhon"
}