@localhost=localhost:4004/odata/v4/main
@id=73658052-2b92-427a-bb5e-9a2a9406931f
@customerId=14101219-2c0f-485b-8475-f09253327210

@productId1=22731459-edea-4622-b51a-c2e0ce91471a 
# produto em estoque
@productId2=22731460-75dd-4203-90bd-672a86dbcba0
GET http://{{localhost}}/SalesOrderHeaders?$filter=id eq {{id}}&$expand=items
Content-Type: application/json

###

POST http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

{
    #"id": "{{id}}",
    "customer_id": "14101219-2c0f-485b-8475-f09253327210",
    "totalAmount": 398,
    "items": [
        {
            "id": "22731459-edea-4622-b51a-c2e0ce91471a",
            "header_id": "{{id}}",
            "product_id": "{{productId1}}",
            "quantity": 10,
            "price": 2.99
        },
        {
           "id": "14101221-456f-4fd5-9b66-684957f66393",
            "header_id": "{{id}}",
            "product_id": "{{productId2}}",
            "quantity": 5,
            "price": 1.99 
        }
    ]
}

###

DELETE  http://{{localhost}}/SalesOrdersHeaders(id={{id}})
Content-Type: application/json

###

PUT http://{{localhost}}/SalesOrdersHeaders(id={{id}})
Content-Type: application/json

###

# Buscar todos os pedidos maiores ou iguais a 2000000 milhões. 

GET http://{{localhost}}/SalesOrdersHeaders?$filter=totalAmount ge 2000000

###
# Buscar todos os pedidos menores ou iguais a 2000000 milhões.
GET http://{{localhost}}/SalesOrdersHeaders?$filter=totalAmount le 2000000

###
# Expandindo os items
GET http://{{localhost}}/SalesOrdersHeaders?$expand=items($expand=product),customer

###
# Expandindo os items, produtos e customers e filtrando
GET http://{{localhost}}/SalesOrdersHeaders?$expand=items($expand=product;$filter=quantity le 30),customer

###
# Selecionar somente customer, id e sales order header
GET http://{{localhost}}/SalesOrdersHeaders?$expand=items($expand=product;$filter=quantity le 30),customer

###
# Selecionar somente customer, id do sales order header
GET http://{{localhost}}/SalesOrdersHeaders?$select=id,customer&$expand=customer($select=email)

###
# Descobrindo a quantidade de registros

GET http://{{localhost}}/SalesOrdersHeaders/$count

###
# Paginando os registros

GET http://{{localhost}}/SalesOrdersHeaders?$skip=5&$top=5

###
# Buscando dados com search

GET http://{{localhost}}/SalesOrdersHeaders?$search=4dvhl