@localhost=localhost:4004/odata/v4/main
@id=3227afd2-1de1-40b8-9af9-351d7f9be023
@customerId=14101219-2c0f-485b-8475-f09253327210

@productId1=22731459-edea-4622-b51a-c2e0ce91471a 
# produto em estoque
@productId2=22731460-75dd-4203-90bd-672a86dbcba0
GET http://{{localhost}}/SalesOrderHeaders?$filter=id eq {{id}}&$expand=items
Content-Type: application/json
Authorization: Basic pedro:130269


###

POST http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json
Authorization: Basic pedro:130269

{
    #"id": "{{id}}",
    "customer_id": "14101219-2c0f-485b-8475-f09253327210",
    "items": [
        {
            "id": "22731459-edea-4622-b51a-c2e0ce91471a",
            "header_id": "{{id}}",
            "product_id": "{{productId1}}",
            "quantity": 10,
            "price": 2.99
        },
        {
           "id": "14101221-456f-4fd5-9b66-684957f66393",
            "header_id": "{{id}}",
            "product_id": "{{productId2}}",
            "quantity": 5,
            "price": 1.99 
        }
    ]
}

###

DELETE  http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json
Authorization: Basic dinei:130269


###

PUT http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json
Authorization: Basic pedro:130269


###

# Buscar todos os pedidos maiores ou iguais a 2000000 milhões. 

GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount ge 2000000
Authorization: Basic pedro:130269


###
# Buscar todos os pedidos menores ou iguais a 2000000 milhões.
GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount le 2000000
Authorization: Basic pedro:130269


###
# Expandindo os items
GET http://{{localhost}}/SalesOrderHeaders?$expand=items($expand=product),customer
Authorization: Basic pedro:130269


###
# Expandindo os items, produtos e customers e filtrando
GET http://{{localhost}}/SalesOrderHeaders?$expand=items($expand=product;$filter=quantity le 30),customer
Authorization: Basic pedro:130269


###
# Selecionar somente customer, id e sales order header
GET http://{{localhost}}/SalesOrderHeaders?$expand=items($expand=product;$filter=quantity le 30),customer
Authorization: Basic pedro:130269


###
# Selecionar somente customer, id do sales order header
GET http://{{localhost}}/SalesOrderHeaders?$select=id,customer&$expand=customer($select=email)
Authorization: Basic pedro:130269


###
# Descobrindo a quantidade de registros

GET http://{{localhost}}/SalesOrderHeaders/$count
Authorization: Basic pedro:130269


###
# Paginando os registros

GET http://{{localhost}}/SalesOrderHeaders?$skip=5&$top=5
Authorization: Basic pedro:130269


###
# Buscando dados com search

GET http://{{localhost}}/SalesOrderHeaders?$search=4dvhl
Authorization: Basic pedro:130269
